version: '3'

services:
  base: &base
    hostname: base
    image: node:boilerplate
    ports: []
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/home/node/app

  swagger:
    hostname: swagger
    image: swaggerapi/swagger-ui
    ports:
      - 5003:8080
    volumes:
      - ./swagger.json:/home/node/app/swagger.json
    environment:
      SWAGGER_JSON: /home/node/app/swagger.json

  app: &app
    <<: *base
    hostname: app
    command: npm run dev
    environment: &env
      NODE_ENV: development
      EXPRESS_PORT: '3003'
      NODE_PATH: '.'
    ports:
      - '3003:3003'

  debug:
    <<: *app
    command: npm run start:debug
    ports:
      - '3003:80'
      - '9229:9229'


  specs:
    <<: *base
    command: /bin/bash -c "npm test"
    environment:
      <<: *env
      NODE_ENV: test
      BASE_URL: 'https://dummy.com.br/v1'

  lint:
    <<: *base
    command: /bin/bash -c "npm run lint"
